# Generated by Django 5.1.7 on 2025-04-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_farmerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdetails',
            name='profile_img',
            field=models.ImageField(upload_to='profile_image'),
        ),
    ]
