# Generated by Django 5.1.7 on 2025-04-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_alter_farmerdetails_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdetails',
            name='farm_name',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
    ]
