# Generated by Django 5.1.7 on 2025-04-07 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_farmerdetails_farm_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerdetails',
            name='farm_name',
        ),
    ]
