# Generated by Django 5.1.7 on 2025-04-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_farmerdetails_farm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
