# Generated by Django 5.1.7 on 2025-04-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0005_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
