# Generated by Django 5.1.7 on 2025-04-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0006_delete_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
